Feature Request: Make /proc/meminfo/ readout optional
justb4/docker-jmeter pull request #61
Opened 2022-05-30 06:03 UTC by Milchschokolade

**Feature/Problem Description:**
/proc/meminfo/ always reads out the memory of the host machine (see https://fabiokung.com/2014/03/13/memory-inside-linux-containers/).  This is a problem when running the container in a cluster environment like Kubernetes or OpenShift.

**Proposed Solution:** 
Add a new, optional command line parameter to control the "freeMem" parameter, which does not get passed to the jmeter call.

2022-05-30 12:05 UTC, justb4 commented
I can see that this may be an issue but isn't this always the case, for example when running multiple Docker Containers and/or assigning a specific memory maximum like with `docker run --memory 512m ...`?

It is hard for me to follow the new optional command line parameter logic. Like the case `--)`.
Suggestion: Isn't it easier to introduce a new variable like `FREE_MEM` which can be passed to the container? If set, its value will override getting `freeMem` from`/proc/meminfo`.

2022-05-31 06:34 UTC, Milchschokolade commented
Im not sure about the problem apprearing with vanilla docker, but with Kubernetes/Openshift, this certainly is an issue. 

The ```---)``` case breaks the loop when no more options are available. As I understand it, this is necessary for null parameters, but I baiscally went with the implementation found [here](https://wiki.bash-hackers.org/scripting/posparams).

> Suggestion: Isn't it easier to introduce a new variable like FREE_MEM which can be passed to the container? If set, its value will override getting freeMem from/proc/meminfo.

This is baiscally what I am trying to do. In line 24, a new parameter "-max_memory <value>" is filtered and assigned to the freeMem variable. The name could of course be altered to "-FREE_MEM", if desired. The rest of the code retrieves the remaining command line parameters, which will then be added to the ```options``` list, which in turn gets passed to jmeter directly in line 64. If no ```-max_memory``` parameter is set, the code will remain as is and use the readout of /proc/meminfo.

2022-05-31 10:26 UTC, mophima commented
I believe I understand now, what you were trying to say. 
I edited the Skript so that it should work with environment variables instead of using a cmd arg. 

It now features three variables: ```JVM_XMS```, ```JVM_XMN``` and ```JVM_XNX``` which can be set. If not, the default of reading out /proc/meminfo should be used.

Is this more what you had in mind?

2022-05-31 11:23 UTC, justb4 commented
Yes, using variables is very common in Docker-based deployments, especially in Kubernetes. This is much more flexible than adapting the entrypoint command line.

Your new script has some problems, see my review, upcoming.

2022-05-31 11:28 UTC, justb4 requested changes
The intention of the script is clear. There are two problems though:

* the `-z` expression is the reverse: when variable _not_ set
* spaces are required like `[ -z ${VAR} ]`

The intended logic, use env vars when set can be more compact/sh-like:

```
freeMem=`awk '/MemAvailable/ { print int($2/1024) }' /proc/meminfo`

[[ -z ${JVM_XMN} ]] && JVM_XMN=$(($freeMem/10*2))
[[ -z ${JVM_XMS} ]] && JVM_XMS=$(($freeMem/10*8))
[[ -z ${JVM_XMX} ]] && JVM_XMX=$(($freeMem/10*8))

export JVM_ARGS="-Xmn${JVM_XMN}m -Xms${JVM_XMS}m -Xmx${JVM_XMX}m"
```
The variable `n` etc are not needed. These lines use `JVM_*` vars when set or from `freeMem`.

2022-06-01 06:40 UTC, Milchschokolade commented
I changed it :)

2022-06-01 11:25 UTC, justb4 commented
Ok, looks good. One last request: can you add a few lines in the README.md to document the three new optional env vars, how and when to use? Thanks! Then we are good to go/merge!

2022-06-03 07:03 UTC, Milchschokolade commented
I added a description to the readme

2022-06-03 13:29 UTC, justb4 approved these changes
Ok, all looks good! Will merge soon.

2022-06-03 13:30 UTC, merged